apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /app1/
        pathType: Prefix
        backend:
          service:
            name: flask1-service
            port:
              number: 5000
      - path: /app2/
        pathType: Prefix
        backend:
          service:
            name: flask2-service
            port:
              number: 5000
